---
title: "Processing the extant data"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---


```{r}
library(ape)
library(dispRity)
set.seed(42)
source("../Functions/read.any.tree.R")
```

## Editing the extant fish tree

This step inputs the tree of living fishes from Rabosky et al 2013 and only keeps one species per family.
The species were chosen based on alphabetical order for each family.

```{r}
## Reading the tree
raw_tree <- read.any.tree("../Data/Raw/Trees/Rabosky.et.al~2013-Nat.Com.tre")

## Reading the list of species selected for each families
list_sp <- read.csv("../Data/Raw/Trees/Living_species_families_for_Rabosky2013.csv", header = TRUE, stringsAsFactor = FALSE)

## Add the row names to the list for cleaning
rownames(list_sp) <- list_sp[,1]

## Match both datasets
cleaned_data <- clean.data(list_sp, raw_tree)
pruned_tree <- cleaned_data$tree

## Converting the sp names into family names
pruned_tree$tip.label <- list_sp[match(pruned_tree$tip.label, list_sp[,1]), 2]
```

### Combining the tree and the spines/body mass data

```{r}
## Reading the spines data
raw_data <- read.csv("../Data/Raw/Collected/Price_ExtantData.csv", header = TRUE, stringsAsFactor = FALSE)
rownames(raw_data) <- raw_data[,1]

## Keeping only the data with phylogeny
cleaned_data <- clean.data(raw_data, pruned_tree)
pruned_data <- cleaned_data$data

## Removing the source and stuff columns
pruned_data <- pruned_data[, c(2, 5,7, 10, 11:13, 15:17, 19:21, 24, 25)]

## Get the armourness
get.armourness <- function(one_row, armour_columns, type = "binary") {

    score <- which(one_row[armour_columns] == 1)
    if(length(score) == 0){
      score <- NULL
    }

    return(ifelse(type == "binary", ifelse(is.null(score), 0, 1), length(score)))
}

binary_armour <- apply(pruned_data, 1, get.armourness, armour_columns = c(6,7,9,10,12,13), type = "binary")
scored_armour <- apply(pruned_data, 1, get.armourness, armour_columns = c(6,7,9,10,12,13), type = "scored")

armour <- cbind("binary" = binary_armour, "scored" = scored_armour)

## Generating the spine data
spine_data <- list("tree" = pruned_tree, "spine_data" = pruned_data, "armour" = armour)

## Saving the data
save(spine_data, file = "../Data/Processed/extant.rda")

```



